services:
  - type: web
    name: luma-backend
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: 239fe6efe77b679864feab7135d16b8c
        sync: false
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: postgres://postgres:Pooh9997748@db.iypqtdzdofthaltggccr.supabase.co:5432/LumaSphere
      - key: ALLOWED_HOSTS
        value: lumasphere-backend.onrender.com,localhost,127.0.0.1
      - key: DJANGO_SECRET_KEY
        value: 239fe6efe77b679864feab7135d16b8c
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
